### ISSUE TITLE
[Feature] 팝업창 닫기

### ISSUE THREAD

**Issue by wjdgh4058** [marketKurly/likelion-market-kurly#28]
## 🌈 작업 브랜치
`feature/28-popup-close`

## 📝 TASK 개요
팝업창 쿠키를 이용해서 오늘 하루동안 닫기 및 일반 닫기

## ✅ To Do 및 진행상황
- [x] jquery 설치
- [x] demo 팝업창 마크업
- [x] demo 닫기 및 쿠키를 이용한 하루동안 안닫기 구현
- [x] demo 에서 확인한 내용 원본에 적용하기
- [x] popup close 완성
