### ISSUE TITLE
[Feature] main-banner swiper

### ISSUE THREAD

**Issue by wjdgh4058** [marketKurly/likelion-market-kurly#29]
## 🌈 작업 브랜치
`feature/29-main-banner-swiper`

## 📝 TASK 개요
main-banner swiper 자동 슬라이드로 적용

## ✅ To Do 및 진행상황
- [x] 슬라이드 화살표 클릭시 이동
- [x] 마지막 슬라이드에서 이동시 처음 슬라이드로 이동
- [x] 화살표를 누르지 않아도 자동 재생
- [x] mouse hover 시 autoplay stop, hover 아닐시 autoplay play
- [x]  mouse hover 시 화살표 나타남 여부 설정
- [x] 화살표 위치 설정 및 마크업
- [x] pagination fraction으로 구현
- [x] pagination 위치 설정
- [x] 키보드 접근 가능하게 하기
