### ISSUE TITLE
[Fix] 메인 페이지 마크업 오류 수정

### ISSUE THREAD

**Issue by wjdgh4058** [marketKurly/likelion-market-kurly#36]
## 🌈 작업 브랜치
`fix/35-markup-fixed-main`

## 📝 TASK 개요
merge 후 발생한 main 페이지 오류 수정

## ✅ To Do 및 진행상황
- [x] 중복된 classname 수정
- [x] main 페이지에 헤더 푸터 추가
- [x] 헤더 푸터 main 페이지로 부터 상대경로 재설정
