### ISSUE TITLE
[Feature] today-recomend-product- swiper

### ISSUE THREAD

**Issue by wjdgh4058** [marketKurly/likelion-market-kurly#46]
## 🌈 작업 브랜치
feature/46-today-recomend-product-swiper

## 📝 TASK 개요
main 페이지에 있는 today-recomend-product swiper 적용

## ✅ To Do 및 진행상황
- [x] 기본 스와이퍼 적용
- [x] 4개씩 묶음으로 이동하게 설정
- [x] 이동 화살표 커스텀
- [] 첫번째  슬라이더에서는 왼쪽 화살표 x 마지막 슬라이더에서는 오른쪽 화살표 x
- [] 키보드 접근
