### ISSUE TITLE
[Feature] 상품 상세 페이지 마크업

### ISSUE THREAD

**Issue by HJY0** [marketKurly/likelion-market-kurly#5]
## 🌈 작업 브랜치
`feature/5-markup-product-detail`

## 📝 TASK 개요
상품 상세 페이지 마크업

## ✅ To Do 및 진행상황

- [ ] 상품 상세 페이지 마크업 (아이콘 수정 예정)
- [x] product-detail-information markup
- [x] product-detail-information css
- [x] product-detail-category markup
- [x] product-detail-category css
- [x] product-detail-description markup
- [x] product-detail-description css
