### ISSUE TITLE
[Feature] add-cart 팝업 이벤트 등록

### ISSUE THREAD

**Issue by wjdgh4058** [marketKurly/likelion-market-kurly#52]
## 🌈 작업 브랜치
feature/52-add-cart-event

## 📝 TASK 개요
add-cart 팝업창 이벤트 등록

## ✅ To Do 및 진행상황
- [x] 장바구니 아이콘 클릭시 팝업창 display: none 해제 
- [x] 닫기버튼 클릭시 팝업창 display: none
- [x] 버튼 클릭시 화면 새로고침 현상 개선
