### ISSUE TITLE
[Feature] 메인 페이지 마크업

### ISSUE THREAD

**Issue by wjdgh4058** [marketKurly/likelion-market-kurly#6]
## 🌈 작업 브랜치
`feature/6-markup-main`

## 📝 TASK 개요
메인 페이지 마크업 & ad 팝업창, cart 팝업창 마크업

## ✅ To Do 및 진행상황
- [x] main page 기본 마크업
- [x] main_banner markup
- [x] today_recommend-product  markup
- [x] Line_banner markup
- [x] today_recommend-product _2 markup
- [x] popup/ ad markup
- [x] popup/ Add cart markup
