### ISSUE TITLE
[Feature] 후기 작성 팝업 글 등록 기능 구현

### ISSUE THREAD

**Issue by HJY0** [marketKurly/likelion-market-kurly#65]
## 🌈 작업 브랜치
`feature/65-review-product-popup`

## 📝 TASK 개요
후기 작성 팝업 내부 기능 구현, data.json 이용해서 글 등록 구현

## ✅ To Do 및 진행상황

- [x] 실시간 글자 수 체크, 보여주기
- [x] textarea 기본 안내 문구 추가
- [x] textarea 클릭하면 문구 숨기기
- [x] 제목과 내용 둘 다 입력 시 등록 버튼 색상 바꾸기
- [x] 제목과 내용 입력 후 등록 버튼 누르면 data.json에 데이터 저장하기
- [x] 저장한 데이터 상세 페이지에 출력해주기
