### ISSUE TITLE
[Feature] swiper 키보드 접근

### ISSUE THREAD

**Issue by wjdgh4058** [marketKurly/likelion-market-kurly#75]
## 🌈 작업 브랜치
feature/75-swiper-keyboard

## 📝 TASK 개요
swiper 키보드 접근 
웹접근성 고려

## ✅ To Do 및 진행상황
- [ ] 총 몇 장의 슬라이드 중 현재 활성화된 슬라이드가 몇 번째 슬라이드 인지 확인 할 수 있게 하기
- [ ] 키보드 tab, back tab으로 모든 슬라이드 접근이 가능하게 하기
- [ ] 무한루프 접근성 고려
