### ISSUE TITLE
[Feature] products json fetch 데이터 가져오기

### ISSUE THREAD

**Issue by wjdgh4058** [marketKurly/likelion-market-kurly#79]
## 🌈 작업 브랜치
feature/79-main-products-fetch

## 📝 TASK 개요
메인 페이지에 있는 products 데이터 json 서버에서 가져오기

## ✅ To Do 및 진행상황
- [x] fetch 로 데이터 읽어오기
- [x] product 에 데이터 적용하기
- [x] 모든 product에 적용
- [x] add-cart 데이터 localstorage 로 이동
- [ ] 수량 체크해서 localstorage 로 이동
